<?php
/**
 * Generated by Haxe 4.3.3
 */

namespace eci;


class EpicQR {
	/**
	 * @var string
	 */
	const IV = "H76\$suq23_po(8sD";
	/**
	 * @var string
	 */
	const KEY = "X_4k\$uq23FSwI.qT";

	/**
	 * @param string $input
	 * 
	 * @return Result
	 */
	public static function decode ($input) {
		$ct = \base64_decode($input);
		$jsonString = \call_user_func("openssl_decrypt", $ct, "aes-128-cbc", "X_4k\$uq23FSwI.qT", 1, "H76\$suq23_po(8sD");
		$_d = \json_decode($jsonString);
		return new Result($_d->epic_no, $_d->unique_generated_id);
	}
}

